# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Jacob Boykin's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "jacob boykin"

# Tagline section text
tagline: >-
    ðŸŽ¸ Music maker and creator ðŸŽ™ï¸

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-facebook"
      text: "Facebook"
      url: "https://www.facebook.com/thejacobboykin"
      alt: "The Jacob Boykin Facebook page"
      title: "Facebook"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://instagram.com/thejacobboykin"
      alt: "The Jacob Boykin Instagram"
      title: "Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-tiktok"
      text: "TikTok"
      url: "https://tiktok.com/@thejacobboykin"
      alt: "The Jacob Boykin TikTok"
      title: "TikTok"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "YouTube"
      url: "https://www.youtube.com/c/BoykinMusic"
      alt: "The Jacob Boykin YouTube channel"
      title: "YouTube"
      target: "_blank"
  - link:
      icon: "fa-brands fa-soundcloud"
      text: "SoundCloud"
      url: "https://www.soundcloud.com/thejacobboykin"
      alt: "The Jacob Boykin SoundCloud"
      title: "SoundCloud"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The URL title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/thejacobboykin"
      title: "Facebook"
      alt: "The Jacob Boykin Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/thejacobboykin"
      title: "Instagram"
      alt: "The Jacob Boykin Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://tiktok.com/@thejacobboykin"
      title: "TikTok"
      alt: "The Jacob Boykin TikTok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/c/BoykinMusic"
      title: "YouTube"
      alt: "The Jacob Boykin YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-soundcloud"
      url: "https://www.soundcloud.com/thejacobboykin"
      title: "SoundCloud"
      alt: "The Jacob Boykin SoundCloud"
      target: "_blank"

# Footer copyright message
# Linkyee is a 100% free, open-source projectâ€”feel free to modify the copyright message as you like. :)
copyright: >
  Â© 2025 Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
